application:
  kafka:
    create-todo:
      topic: create-todo
      consumer-client-id: ${application.kafka.create-todo.topic}-consumer-client
      consumer-group-id: ${application.kafka.create-todo.topic}-consumer-group

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific:
          avro:
            reader: true